name: project2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: npm install
    - name: lint
      run: npx eslint
    - name: test
      run: npm test
     
