name: project2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: make install
    - name: lint
      run: make lint 
    - name: test
      run: make test
    - name: test-coverage
      run: make test-coverage
