name: project2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install
    - name: lint
      run: npx eslint . 
    - name: test
      run: npm test
     
