name: project2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: make install
    - name: lint
      run: make lint 
    - name: test
      run: make test
    - name: test-coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
          CC_TEST_REPORTER_ID: ${{eb438f17af84c750f64ec19f0d4f982c7e46678781eb7c96eb94a783882e1da5}}
      with:
          coverageCommand: make test-coverage
